### PR TITLE
Improved XML comparison in regression check (after IXML is replaced with SXML in abap2xlsx)

### PR DESCRIPTION
**Pull request by sandraros**
The order of xmlns "attributes" cannot be chosen with SXML, hence ZDEMO_EXCEL_CHECKER is rewritten to NOT compare the order. Related to https://github.com/abap2xlsx/abap2xlsx/issues/632.

### CODE REVIEW

**Comment by larshp** [comment]
looks like there are a lot of whitespace(?) changes in this PR which does not relate to replacing ixml with sxml? Suggest doing a PR with the actual functional changes only. 

Can always do a different with whitespace changes, plus whitespace is opinionated and not enforced, so better just keeping it as is?

**Comment by larshp** [comment]
I suggest disabling ABAP Cleaner in all development scenarios

**Comment by sandraros** [comment]
Concerning the pretty print, I guess there's no ideal solution for now (maybe the best one is to have one workspace per project), except that I should check the DIFF of commits in case the project is Git-based, which I didn't do. My bad.

ABAP Cleaner reverted.

Note that the core of the PR is the block "IF normalize_xml = abap_true."

**Review by larshp — APPROVED** [review]
lgtm

**Pull request merged**
