### PR TITLE
ZDEMO_EXCEL2: add change_cell_style showcase

### LINKED ISSUE #73: ZDEMO_EXCEL2 don't demonstrate lo_worksheet->change_cell_style
many different styles are shown but no change_cell_style
also change_cell_style was needed for https://github.com/abap2xlsx/abap2xlsx/issues/1259

### PR DESCRIPTION
**Pull request by bigld**
image

fixes #73

needed to test https://github.com/abap2xlsx/abap2xlsx/pull/1260

### CODE REVIEW

**Review by larshp — APPROVED** [review]
lgtm

**Comment by sandraros** [comment]
Could you run `zdemo_excel_checker` (regression checker) to regenerate the new files [zdemo_excel2.w3mi.data.xlsx](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel2.w3mi.data.xlsx) and [zdemo_excel15_02.w3mi.data.xlsx](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel15_02.w3mi.data.xlsx)? (Choose any folder on your laptop, run the program, the 2 programs `zdemo_excel2` and `zdemo_excel15_02` should be in red status, click on the Save button to upload the 2 changed Excel files in the Web repository, and push the changes to your branch)

**Comment by larshp** [comment]
> Could you run `zdemo_excel_checker` (regression checker) to regenerate the new files [zdemo_excel2.w3mi.data.xlsx](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel2.w3mi.data.xlsx) and [zdemo_excel15_02.w3mi.data.xlsx](https://github.com/abap2xlsx/demos/blob/main/src/zdemo_excel15_02.w3mi.data.xlsx)? (Choose any folder on your laptop, run the program, the 2 programs `zdemo_excel2` and `zdemo_excel15_02` should be in red status, click on the Save button to upload the 2 changed Excel files in the Web repository, and push the changes to your branch)

if we get stuff like https://github.com/abap2xlsx/demos/pull/69 decided/merged, then one day it should be possible to have github actions automatically generate the `xlsx` files, and check/show differences if any

**Comment by larshp** [comment]
@bigld can you help updating the branch, or setting "allow changes by maintainers"

**Comment by larshp** [comment]
lets go

**Pull request merged**
